=== nivikundem/MuleXLStoXML/xlstoxml/src/main/resources/ISBNMessage.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="ML-MessageList">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="M-Message">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="ON-OrderNo" type="xs:string" minOccurs="1"/>
							<xs:element name="CN-ClientName" type="xs:string" minOccurs="1"/>
							<xs:element name="CD-ClientDetails" minOccurs="1">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="FN-FirstName" type="xs:string" minOccurs="1"/>
										<xs:element name="LN-LastName" type="xs:string" minOccurs="1"/>
										<xs:element name="A-Age" type="xs:string" minOccurs="1"/>
										<xs:element name="C-County" type="xs:string" minOccurs="1"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>				
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== nivikundem/MuleXLStoXML/xlstoxml/src/main/resources/ISBNMessage.xml
<?xml version="1.0" encoding="UTF-8"?>
<ML-MessageList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ISBNMessage.xsd">
  <M-Message>
    <ON-OrderNo>ON-OrderNo</ON-OrderNo>
    <CN-ClientName>CN-ClientName</CN-ClientName>
    <CD-ClientDetails>
      <FN-FirstName>FN-FirstName</FN-FirstName>
      <LN-LastName>LN-LastName</LN-LastName>
      <A-Age>A-Age</A-Age>
      <C-County>C-County</C-County>
    </CD-ClientDetails>
  </M-Message>
</ML-MessageList>
